baseURL = "https://soliloquier.github.io/"
title = "A Teahouse"
theme = "plan9"
enableEmoji = false

[menu]
  [[menu.main]]
    identifier = "home"
    name = "Home"
    url = "/"
    weight = 5

  [[menu.main]]
    identifier = "posts"
    name = "Posts"
    url = "/posts"
    weight = 10

  [[menu.main]]
    identifer = "library"
    name = "Library"
    url = "/books"
    weight = 15